github:
  is_project_page: false

title: Arnav Tolat
description: Arnav Tolat - Dartmouth Junior Studying CS, Math, and Statistics
plugins:
  - jemoji
  - jekyll-remote-theme
 
remote_theme: jekyll/minima

