theme: jekyll-theme-hacker
is_project_page: false
title: Arnav Tolat 
description: I'm a Dartmouth Junior Studying CS, Math, and Statistics With a Passion for Impact 
plugins:
  - jemoji
  
github:
  is_project_page: false
  
  
