theme: jekyll-theme-hacker
title: Hi, I'm Arnav
description: I'm a Dartmouth Junior Studying CS, Math, and Statistics who is Passionate About Building Impactful Products 
plugins:
  - jemoji
  
github:
  is_project_page: false
